### ISSUE TITLE
[Error] 디폴트 프로필 사진

### ISSUE THREAD

**Issue by chaeyoung97** [chaeyoung97/restagram#14]
`if(imageRepo.existsByUserId(id)) {
			Images profileImage =  imageRepo.findByUserIdAndImageName(id, "profile.jpg");
			if(profileImage == null)	//NPE 발생하여 추가해 두었습니다.
				return;
			model.addAttribute("ImageName", profileImage.getImageName());
			model.addAttribute("ImageURL", profileImage.getImageURL());			
		}`

프로필 이미지를 가져오는 부분에서 프로필이미지가  null일 경우 NPE가 발생하여 일단 if문 처리를 해두고,  NPE가 발생하지 않도록 처음 유저를 생성할 때 디폴트이미지를 넣어두었습니다

`@Builder
	public Users(String name, String username, String password, String email) {
		this.name = name;
		this.username = username;
		this.password = password;
		this.email = email;
		if(name.equals("admin"))
			this.role=Role.ADMIN;
		else
			this.role = Role.USER;
		profileImage = "/imgs/defaultImage.jpg";
	}`

**Comment by niveus323** [comment]
게시물에 User객체를 등록하면서 수정해야 하는걸 잊고있었네요.
imageRepo의 함수를 imageRepo.existsByUserIdAndIamgeName(id,"profile.jpg")로 변경하여 해결하였습니다.
