### ISSUE TITLE
[Error] 수정 요청

### ISSUE THREAD

**Issue by chaeyoung97** [chaeyoung97/restagram#17]
![image](https://user-images.githubusercontent.com/47133664/104198178-41f7f300-5469-11eb-9cea-5594f2d257c0.png)
![image](https://user-images.githubusercontent.com/47133664/104198280-648a0c00-5469-11eb-905b-7c2c86d5dc9c.png)

프로필 수정 과정에서 첫번째 사진처럼 update가 제대로 이루어지고 있지 않습니다. 기존 프로필 이미지가 삭제되지 않는걸로 보아 updateProfileImage 함수가 아닌 save함수가 불러지는 것 같은데 어디서 동작하고 있는지 찾지 못하여 득행님이 직접 수정해주셔야 할 것 같아요!

**Comment by niveus323** [comment]
해결완료했습니다
